<?php

use Illuminate\Database\Seeder;

class BrandTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $digikalaBrands = [
            "Brands"=> [
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر چشمه",
                    "EnTitle"=> "Cheshmeh",
                    "ShowType"=> 0,
                    "LogoPath"=> "Image/Webstore/Brand/B_1579/Original/CHESHMEH.png",
                    "Code"=> "Cheshmeh-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1579EditDateTime => 6/8/2016 2=>14=>14 PMEditorId => 3585183IsActive => 1FaTitle => نشر چشمهEnTitle => CheshmehShowtype => 0LogoPath => Image/Webstore/Brand/B_1579/Original/CHESHMEH.pngCode => Cheshmeh-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1579,
                    "EditDateTime"=> "2016-06-08T14=>14=>14.607",
                    "EditorId"=> 3585183,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "انتشارات کارنامه",
                    "EnTitle"=> "Karnameh Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Karnameh-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2243EditDateTime => 1/12/2016 12=>39=>52 PMEditorId => 716236IsActive => 1FaTitle => انتشارات کارنامهEnTitle => Karnameh PubShowtype => 0LogoPath => Code => Karnameh-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2243,
                    "EditDateTime"=> "2016-01-12T12=>39=>52.32",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر مرکز",
                    "EnTitle"=> "Markaz",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Markaz-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1585EditDateTime => 2/16/2015 2=>49=>00 PMEditorId => 716358IsActive => 1FaTitle => نشر مرکزEnTitle => MarkazShowtype => 0LogoPath => Code => Markaz-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1585,
                    "EditDateTime"=> "2015-02-16T14=>49=>00",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر امیر کبیر",
                    "EnTitle"=> "Amir Kabir",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Amir-Kabir-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1736EditDateTime => 5/7/2015 11=>21=>00 AMEditorId => 716358IsActive => 1FaTitle => نشر امیر کبیرEnTitle => Amir KabirShowtype => 0LogoPath => Code => Amir-Kabir-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1736,
                    "EditDateTime"=> "2015-05-07T11=>21=>00",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر نیلوفر",
                    "EnTitle"=> "Niloufar",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Niloufar-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1586EditDateTime => 2/16/2015 2=>50=>00 PMEditorId => 716358IsActive => 1FaTitle => نشر نیلوفرEnTitle => NiloufarShowtype => 0LogoPath => Code => Niloufar-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1586,
                    "EditDateTime"=> "2015-02-16T14=>50=>00",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "انتشارات فرهنگ معاصر",
                    "EnTitle"=> "Farhang Moaser Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Farhang-Moaser-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2680EditDateTime => 4/17/2016 11=>15=>43 AMEditorId => 835069IsActive => 1FaTitle => انتشارات فرهنگ معاصرEnTitle => Farhang Moaser PubShowtype => 0LogoPath => Code => Farhang-Moaser-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2680,
                    "EditDateTime"=> "2016-04-17T11=>15=>43.06",
                    "EditorId"=> 835069,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر نی",
                    "EnTitle"=> "Ney",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Ney-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1580EditDateTime => 2/16/2015 2=>45=>00 PMEditorId => 716358IsActive => 1FaTitle => نشر نیEnTitle => NeyShowtype => 0LogoPath => Code => Ney-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1580,
                    "EditDateTime"=> "2015-02-16T14=>45=>00",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "معین",
                    "EnTitle"=> "Moein",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Moein-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1982EditDateTime => 7/21/2015 10=>26=>46 AMEditorId => 716358IsActive => 1FaTitle => معینEnTitle => MoeinShowtype => 0LogoPath => Code => Moein-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1982,
                    "EditDateTime"=> "2015-07-21T10=>26=>46.82",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "انتشارات خوارزمی",
                    "EnTitle"=> "Kharazmi Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Kharazmi-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2229EditDateTime => 1/12/2016 12=>42=>55 PMEditorId => 716236IsActive => 1FaTitle => انتشارات خوارزمیEnTitle => Kharazmi PubShowtype => 0LogoPath => Code => Kharazmi-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2229,
                    "EditDateTime"=> "2016-01-12T12=>42=>55.407",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر نسل نواندیش",
                    "EnTitle"=> "Nasle Nowandish",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Nasle-Nowandish-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1584EditDateTime => 2/16/2015 2=>48=>00 PMEditorId => 716358IsActive => 1FaTitle => نشر نسل نواندیشEnTitle => Nasle NowandishShowtype => 0LogoPath => Code => Nasle-Nowandish-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1584,
                    "EditDateTime"=> "2015-02-16T14=>48=>00",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر ققنوس",
                    "EnTitle"=> "Ghoghnoos Spread",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Ghoghnoos-Spread-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2008EditDateTime => 8/19/2015 11=>05=>07 AMEditorId => 716236IsActive => 1FaTitle => نشر ققنوسEnTitle => Ghoghnoos SpreadShowtype => 0LogoPath => Code => Ghoghnoos-Spread-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2008,
                    "EditDateTime"=> "2015-08-19T11=>05=>07.803",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "انتشارات هرمس",
                    "EnTitle"=> "Hermes Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Hermes-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1380EditDateTime => 4/25/2016 12=>48=>52 PMEditorId => 716236IsActive => 1FaTitle => انتشارات هرمسEnTitle => Hermes PubShowtype => 0LogoPath => Code => Hermes-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1380,
                    "EditDateTime"=> "2016-04-25T12=>48=>52.203",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر نگاه",
                    "EnTitle"=> "Negah",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Negah-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1581EditDateTime => 2/16/2015 2=>46=>00 PMEditorId => 716358IsActive => 1FaTitle => نشر نگاهEnTitle => NegahShowtype => 0LogoPath => Code => Negah-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1581,
                    "EditDateTime"=> "2015-02-16T14=>46=>00",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر علمی فرهنگی",
                    "EnTitle"=> "Nashre Elmi Farhangi",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Nashre-Elmi-Farhangi-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2128EditDateTime => 10/4/2015 9=>28=>29 AMEditorId => 716236IsActive => 1FaTitle => نشر علمی فرهنگیEnTitle => Nashre Elmi FarhangiShowtype => 0LogoPath => Code => Nashre-Elmi-Farhangi-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2128,
                    "EditDateTime"=> "2015-10-04T09=>28=>29.393",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "انتشارات سوره مهر",
                    "EnTitle"=> "Sooremehr Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Sooremehr-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2225EditDateTime => 1/12/2016 12=>43=>05 PMEditorId => 716236IsActive => 1FaTitle => انتشارات سوره مهرEnTitle => Sooremehr PubShowtype => 0LogoPath => Code => Sooremehr-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2225,
                    "EditDateTime"=> "2016-01-12T12=>43=>05.64",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "انتشارات طرح نو",
                    "EnTitle"=> "Tarheh No Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Tarheh-No-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2527EditDateTime => 1/27/2016 11=>10=>09 AMEditorId => 716358IsActive => 1FaTitle => انتشارات طرح نوEnTitle => Tarheh No PubShowtype => 0LogoPath => Code => Tarheh-No-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2527,
                    "EditDateTime"=> "2016-01-27T11=>10=>09.16",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "انتشارات سخن",
                    "EnTitle"=> "Sokhan Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Sokhan-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2216EditDateTime => 1/12/2016 12=>43=>10 PMEditorId => 716236IsActive => 1FaTitle => انتشارات سخنEnTitle => Sokhan PubShowtype => 0LogoPath => Code => Sokhan-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2216,
                    "EditDateTime"=> "2016-01-12T12=>43=>10.897",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "سروش",
                    "EnTitle"=> "Soroush",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Soroush",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1004EditDateTime => 9/18/2013 5=>22=>00 PMEditorId => 1IsActive => 1FaTitle => سروشEnTitle => SoroushShowtype => 0LogoPath => Code => SoroushOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1004,
                    "EditDateTime"=> "2013-09-18T17=>22=>00",
                    "EditorId"=> 1,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر قطره",
                    "EnTitle"=> "Nashre Ghatreh",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Nashre-Ghatreh-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2593EditDateTime => 2/9/2016 12=>16=>51 PMEditorId => 716358IsActive => 1FaTitle => نشر قطرهEnTitle => Nashre GhatrehShowtype => 0LogoPath => Code => Nashre-Ghatreh-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2593,
                    "EditDateTime"=> "2016-02-09T12=>16=>51.903",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر ثالث",
                    "EnTitle"=> "Saless",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Saless-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2291EditDateTime => 11/7/2015 4=>48=>50 PMEditorId => 716236IsActive => 1FaTitle => نشر ثالثEnTitle => SalessShowtype => 0LogoPath => Code => Saless-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2291,
                    "EditDateTime"=> "2015-11-07T16=>48=>50.39",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر یساولی",
                    "EnTitle"=> "Yassavoli",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Yassavoli-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1829EditDateTime => 7/4/2015 3=>52=>04 PMEditorId => 716236IsActive => 1FaTitle => نشر یساولیEnTitle => YassavoliShowtype => 0LogoPath => Code => Yassavoli-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1829,
                    "EditDateTime"=> "2015-07-04T15=>52=>04.947",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر بیدگل",
                    "EnTitle"=> "Bidgol",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Bidgol-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2261EditDateTime => 11/7/2015 4=>55=>35 PMEditorId => 716236IsActive => 1FaTitle => نشر بیدگلEnTitle => BidgolShowtype => 0LogoPath => Code => Bidgol-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2261,
                    "EditDateTime"=> "2015-11-07T16=>55=>35.687",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر نیستان",
                    "EnTitle"=> "Neyestan",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Neyestan-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1791EditDateTime => 5/18/2015 2=>29=>00 PMEditorId => 716358IsActive => 1FaTitle => نشر نیستانEnTitle => NeyestanShowtype => 0LogoPath => Code => Neyestan-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1791,
                    "EditDateTime"=> "2015-05-18T14=>29=>00",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر تیسا",
                    "EnTitle"=> "Teesa",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Teesa-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1587EditDateTime => 2/16/2015 2=>50=>00 PMEditorId => 716358IsActive => 1FaTitle => نشر تیساEnTitle => TeesaShowtype => 0LogoPath => Code => Teesa-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1587,
                    "EditDateTime"=> "2015-02-16T14=>50=>00",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر افق",
                    "EnTitle"=> "Ofogh",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Ofogh-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1706EditDateTime => 4/26/2015 1=>23=>00 PMEditorId => 716236IsActive => 1FaTitle => نشر افقEnTitle => OfoghShowtype => 0LogoPath => Code => Ofogh-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1706,
                    "EditDateTime"=> "2015-04-26T13=>23=>00",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "انتشارات گل آقا",
                    "EnTitle"=> "Gol Agha Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Gol-Agha-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2656EditDateTime => 3/1/2016 4=>07=>28 PMEditorId => 716358IsActive => 1FaTitle => انتشارات گل آقاEnTitle => Gol Agha PubShowtype => 0LogoPath => Code => Gol-Agha-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2656,
                    "EditDateTime"=> "2016-03-01T16=>07=>28.29",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر شادان",
                    "EnTitle"=> "Shadan",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Shadan-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1722EditDateTime => 5/4/2015 11=>21=>00 AMEditorId => 716358IsActive => 1FaTitle => نشر شادانEnTitle => ShadanShowtype => 0LogoPath => Code => Shadan-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1722,
                    "EditDateTime"=> "2015-05-04T11=>21=>00",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "انتشارات قدیانی",
                    "EnTitle"=> "Ghadyani Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Ghadyani-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2226EditDateTime => 1/12/2016 12=>43=>02 PMEditorId => 716236IsActive => 1FaTitle => انتشارات قدیانیEnTitle => Ghadyani PubShowtype => 0LogoPath => Code => Ghadyani-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2226,
                    "EditDateTime"=> "2016-01-12T12=>43=>02.863",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر ویدا",
                    "EnTitle"=> "Vida",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Vida-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1711EditDateTime => 4/27/2015 11=>34=>00 AMEditorId => 716358IsActive => 1FaTitle => نشر ویداEnTitle => VidaShowtype => 0LogoPath => Code => Vida-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1711,
                    "EditDateTime"=> "2015-04-27T11=>34=>00",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "انتشارات آوند دانش",
                    "EnTitle"=> "Avand Danesh Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Avand-Danesh-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2227EditDateTime => 1/12/2016 12=>43=>00 PMEditorId => 716236IsActive => 1FaTitle => انتشارات آوند دانشEnTitle => Avand Danesh PubShowtype => 0LogoPath => Code => Avand-Danesh-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2227,
                    "EditDateTime"=> "2016-01-12T12=>43=>00.523",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "انتشارات کلید آموزش",
                    "EnTitle"=> "Kelid Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Kelid-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1885EditDateTime => 1/12/2016 12=>43=>12 PMEditorId => 716236IsActive => 1FaTitle => انتشارات کلید آموزشEnTitle => Kelid PubShowtype => 0LogoPath => Code => Kelid-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1885,
                    "EditDateTime"=> "2016-01-12T12=>43=>12.753",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر ماهی",
                    "EnTitle"=> "Mahi",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Mahi-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1583EditDateTime => 2/16/2015 2=>47=>00 PMEditorId => 716358IsActive => 1FaTitle => نشر ماهیEnTitle => MahiShowtype => 0LogoPath => Code => Mahi-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1583,
                    "EditDateTime"=> "2015-02-16T14=>47=>00",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر سپاس",
                    "EnTitle"=> "Sepas",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Sepas-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1828EditDateTime => 5/28/2015 11=>31=>15 AMEditorId => 716236IsActive => 1FaTitle => نشر سپاسEnTitle => SepasShowtype => 0LogoPath => Code => Sepas-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1828,
                    "EditDateTime"=> "2015-05-28T11=>31=>15.253",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر بهنام",
                    "EnTitle"=> "Behnam",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Behnam-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1705EditDateTime => 4/26/2015 1=>23=>00 PMEditorId => 716236IsActive => 1FaTitle => نشر بهنامEnTitle => BehnamShowtype => 0LogoPath => Code => Behnam-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1705,
                    "EditDateTime"=> "2015-04-26T13=>23=>00",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "دیباگران",
                    "EnTitle"=> "Dibagaran",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Dibagaran-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 1895EditDateTime => 6/13/2015 2=>04=>50 PMEditorId => 716236IsActive => 1FaTitle => دیباگرانEnTitle => DibagaranShowtype => 0LogoPath => Code => Dibagaran-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 1895,
                    "EditDateTime"=> "2015-06-13T14=>04=>50.47",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "گاج",
                    "EnTitle"=> "Gaj",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Gaj-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2017EditDateTime => 8/29/2015 10=>38=>02 AMEditorId => 716236IsActive => 1FaTitle => گاجEnTitle => GajShowtype => 0LogoPath => Code => Gaj-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2017,
                    "EditDateTime"=> "2015-08-29T10=>38=>02.49",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "قلم چی",
                    "EnTitle"=> "Ghalamchi",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Ghalamchi-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2032EditDateTime => 9/1/2015 5=>42=>58 PMEditorId => 716236IsActive => 1FaTitle => قلم چیEnTitle => GhalamchiShowtype => 0LogoPath => Code => Ghalamchi-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2032,
                    "EditDateTime"=> "2015-09-01T17=>42=>58.963",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "خیلی سبز",
                    "EnTitle"=> "Kheilisabz",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Kheilisabz-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2031EditDateTime => 9/1/2015 5=>41=>11 PMEditorId => 716236IsActive => 1FaTitle => خیلی سبزEnTitle => KheilisabzShowtype => 0LogoPath => Code => Kheilisabz-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2031,
                    "EditDateTime"=> "2015-09-01T17=>41=>11.573",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "کلاغ سپید",
                    "EnTitle"=> "Kalagh Sepid",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Kalagh-Sepid-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2025EditDateTime => 8/31/2015 2=>06=>08 PMEditorId => 716236IsActive => 1FaTitle => کلاغ سپیدEnTitle => Kalagh SepidShowtype => 0LogoPath => Code => Kalagh-Sepid-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2025,
                    "EditDateTime"=> "2015-08-31T14=>06=>08.94",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر الگو",
                    "EnTitle"=> "Nashre Olgoo",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Nashre-Olgoo-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2033EditDateTime => 9/2/2015 12=>23=>45 PMEditorId => 716236IsActive => 1FaTitle => نشر الگوEnTitle => Nashre OlgooShowtype => 0LogoPath => Code => Nashre-Olgoo-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2033,
                    "EditDateTime"=> "2015-09-02T12=>23=>45.5",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "مبتکران",
                    "EnTitle"=> "Mobtakeran",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Mobtakeran-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2049EditDateTime => 9/6/2015 4=>51=>51 PMEditorId => 716236IsActive => 1FaTitle => مبتکرانEnTitle => MobtakeranShowtype => 0LogoPath => Code => Mobtakeran-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2049,
                    "EditDateTime"=> "2015-09-06T16=>51=>51.34",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "مهر و ماه",
                    "EnTitle"=> "Mehr o Mah",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Mehr-o-Mah-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2046EditDateTime => 9/6/2015 4=>53=>52 PMEditorId => 716236IsActive => 1FaTitle => مهر و ماهEnTitle => Mehr o MahShowtype => 0LogoPath => Code => Mehr-o-Mah-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2046,
                    "EditDateTime"=> "2015-09-06T16=>53=>52.753",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "منتشران",
                    "EnTitle"=> "Montasheran",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Montasheran-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2050EditDateTime => 9/6/2015 4=>55=>39 PMEditorId => 716236IsActive => 1FaTitle => منتشرانEnTitle => MontasheranShowtype => 0LogoPath => Code => Montasheran-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2050,
                    "EditDateTime"=> "2015-09-06T16=>55=>39.647",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "جویامجد",
                    "EnTitle"=> "Jooyamajd",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Jooyamajd-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2054EditDateTime => 9/7/2015 3=>24=>48 PMEditorId => 716236IsActive => 1FaTitle => جویامجدEnTitle => JooyamajdShowtype => 0LogoPath => Code => Jooyamajd-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2054,
                    "EditDateTime"=> "2015-09-07T15=>24=>48.397",
                    "EditorId"=> 716236,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "نشر گل واژه",
                    "EnTitle"=> "Golvazheh Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Golvazheh-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2334EditDateTime => 11/29/2015 8=>39=>55 AMEditorId => 716358IsActive => 1FaTitle => نشر گل واژهEnTitle => Golvazheh PubShowtype => 0LogoPath => Code => Golvazheh-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2334,
                    "EditDateTime"=> "2015-11-29T08=>39=>55.993",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ],
                [
                    "Row"=> 0,
                    "FaTitle"=> "انتشارات علامه حلی",
                    "EnTitle"=> "Alameh Heli Pub",
                    "ShowType"=> 0,
                    "LogoPath"=> "",
                    "Code"=> "Alameh-Heli-Pub-Brand",
                    "DefaultSort"=> 0,
                    "OldId"=> 0,
                    "Url"=> "",
                    "Description"=> "",
                    "Alt"=> "",
                    "ImageTitle"=> "",
                    "Caption"=> "",
                    "CategoryTitle"=> null,
                    "CategoryId"=> 0,
                    "CategoryBrands"=> null,
                    "Products"=> null,
                    "LogString"=> "Id => 2392EditDateTime => 1/7/2016 9=>11=>59 AMEditorId => 716358IsActive => 1FaTitle => انتشارات علامه حلیEnTitle => Alameh Heli PubShowtype => 0LogoPath => Code => Alameh-Heli-Pub-BrandOldId => 0Url => Description => Alt => ImageTitle => Caption => ",
                    "IsShowWebSite"=> true,
                    "Id"=> 2392,
                    "EditDateTime"=> "2016-01-07T09=>11=>59.007",
                    "EditorId"=> 716358,
                    "IsActive"=> 1
                ]
            ]
        ];
        $brands = array_map(function($e){
            return [
                'english_name'=>$e['EnTitle'],
                'persian_name'=>$e['FaTitle']
            ];
        },$digikalaBrands['Brands']);

        \App\Brand::insert($brands);
    }
}
